### ISSUE TITLE
Modes Not Being Displayed

### ISSUE THREAD

**Issue by Sinpure** [Kamiloo13/CS2_ChangeLevelChat#1]
When updating the creation config (ChangeLevelChat.json) to include configs, none are displayed in game. Have tried with .cfg and without, unclear exactly how this is meant to be structured?

Appreciate any assistance, thanks!

![image](https://github.com/Kamiloo13/CS2_ChangeLevelChat/assets/167186978/4ede6936-ab1e-4716-84c8-bce01ee38e61)

**Comment by Kamiloo13** [comment]
Hey,
Thanks for downloading my plugin!

I just tested it on the latest CS2 version and it's still working fine for me. 

---

You probably ran into a syntax error in your config because of the comma after:
```
...
"armsrace",
"prac", <----
],
...
```

and

```
...
"Workshop Maps": [
"de_biome", <----
],
...
```

The JSON parser is extremely strict about comma placement, which is why it is recommended to use programs like Visual Studio Code, which make coding much easier as it highlights such errors (Notepad++ is bad for this purpose as it doesn't detect such errors).

Your error in the server console probably looks something like this:
![image](https://github.com/Kamiloo13/CS2_ChangeLevelChat/assets/79232750/cdb5a790-54c2-48b3-8c05-dd0c56e735d2)

---

If you were to switch from Notepad++ to VSC, it would look something like this:
![image](https://github.com/Kamiloo13/CS2_ChangeLevelChat/assets/79232750/87a1ce18-8e28-4d4d-af31-c58cb7a3be90)

Also, I've included an example configuration in the README.

Hope it solved your issue, if you still have any problems with the plugin, then please provide the version of CSSharp and Metamod that you are using.
